services:
  app:
    build: ./
    ports: 
      - 3000:3000
    environment:
      MONGO_URI: mongodb://db:27017/
      MONGO_DBNAME: sg
    depends_on:
      - db
  db:
    image: mongo:4.0-xenial
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - sg:/data/db
  
volumes:
  sg: 


